// This file is auto-generated by mockupPreviewPlugin.ts.
type ModuleMap = Record<string, () => Promise<Record<string, unknown>>>;
export const modules: ModuleMap = {
  "./components/mockups/fluxo-layouts/LeftSidebar.tsx": () => import("../components/mockups/fluxo-layouts/LeftSidebar.tsx"),
  "./components/mockups/fluxo-layouts/TopStrip.tsx": () => import("../components/mockups/fluxo-layouts/TopStrip.tsx"),
  "./components/mockups/fluxo-layouts/UnifiedFeed.tsx": () => import("../components/mockups/fluxo-layouts/UnifiedFeed.tsx")
};
